# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7d360fcf1422c2476bdd1a24e201325dafffb0527aeaf71040699e0c1228f9965471dd0dc18aad345ae5b5fad32b2e2f9eb2fa2631003f770e909460ebb58a

test:
  secret_key_base: e5b013a25ea6536ea4e165e41e7a4bb75a7a6215321bcdae9260d64d492bc1c6a4e80e716b293e2d908f66c547c3a558be5b863780cd12870ad67fd5f496477d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
